### PR TITLE
Improvements for mainline

### PR DESCRIPTION
**Pull request by foxel**
Some improvements from my side excluding the TTS adaptation:
* binary sensors are now really binary
* rtsp links are obtained from the camera, fixes issues with no high res stream
* device info has connections defined so that it can merge with the same devices from other integrations
* camera now supports stream integration

### CODE REVIEW

**Comment by roleoroleo** [comment]
Thanks for your contribution!

**Comment by vin-w** [comment]
I just updated to latest code with camera supports stream integration
then the live streaming in hass does not work (a blank white screen in the camera view)

Once I have removed the code below, the streaming works again for me.
Could we make this configurable?
```
    @property
    def supported_features(self) -> int:
        """Return supported features."""
        return SUPPORT_STREAM
```

**Comment by foxel** [comment]
@vin-w this piece of coffee just says that the camera is capable of providing a streaming URL. 
You need to check that your HA stream integration works 
 See requirements and details at https://www.home-assistant.io/integrations/stream/

**Comment by vin-w** [comment]
@foxel Today I have fetched latest code + restarted the docker stack, it works now! 
With the "Preload stream" checked, I don't have any more drop frame.

Thanks again for your code and make a happy home here.

**Pull request merged**
